language: go
install:
  - curl -sSo gae_sdk.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.24.zip
  - unzip -q gae_sdk.zip
script:
  - ./go_appengine/goapp test -v ./endpoints
